COMMENT ON COLUMN acs2019_5yr.geoheader.fileid IS 'Always equal to ACS Summary File identification';
COMMENT ON COLUMN dec2010_pl94.geoheader.FILEID IS 'File Identification';
COMMENT ON COLUMN dec2010_pl94.geoheader.STUSAB IS 'State/U.S. Abbreviation (USPS)';
COMMENT ON COLUMN dec2010_pl94.geoheader.SUMLEV IS 'Summary Level';
COMMENT ON COLUMN dec2010_pl94.geoheader.GEOCOMP IS 'Geographic Component';
COMMENT ON COLUMN dec2010_pl94.geoheader.CHARITER IS 'Characteristic Iteration';
COMMENT ON COLUMN dec2010_pl94.geoheader.CIFSN IS 'Characteristic Iteration File Sequence Number';
COMMENT ON COLUMN dec2010_pl94.geoheader.LOGRECNO IS 'Logical Record Number';
COMMENT ON COLUMN dec2010_pl94.geoheader.REGION IS 'Region';
COMMENT ON COLUMN dec2010_pl94.geoheader.DIVISION IS 'Division';
COMMENT ON COLUMN dec2010_pl94.geoheader.STATE IS 'State (FIPS)';
COMMENT ON COLUMN dec2010_pl94.geoheader.COUNTY IS 'County';
COMMENT ON COLUMN dec2010_pl94.geoheader.COUNTYCC IS 'FIPS County Class Code';
COMMENT ON COLUMN dec2010_pl94.geoheader.COUNTYSC IS 'County Size Code';
COMMENT ON COLUMN dec2010_pl94.geoheader.COUSUB IS 'County Subdivision (FIPS)';
COMMENT ON COLUMN dec2010_pl94.geoheader.COUSUBCC IS 'FIPS County Subdivision Class Code';
COMMENT ON COLUMN dec2010_pl94.geoheader.COUSUBSC IS 'County Subdivision Size Code';
COMMENT ON COLUMN dec2010_pl94.geoheader.PLACE IS 'Place (FIPS)';
COMMENT ON COLUMN dec2010_pl94.geoheader.PLACECC IS 'FIPS Place Class Code';
COMMENT ON COLUMN dec2010_pl94.geoheader.PLACESC IS 'Place Size Code';
COMMENT ON COLUMN dec2010_pl94.geoheader.TRACT IS 'Census Tract';
COMMENT ON COLUMN dec2010_pl94.geoheader.BLKGRP IS 'Block Group';
COMMENT ON COLUMN dec2010_pl94.geoheader.BLOCK IS 'Block';
COMMENT ON COLUMN dec2010_pl94.geoheader.IUC IS 'Internal Use Code';
COMMENT ON COLUMN dec2010_pl94.geoheader.CONCIT IS 'Consolidated City (FIPS)';
COMMENT ON COLUMN dec2010_pl94.geoheader.CONCITCC IS 'FIPS Consolidated City Class Code';
COMMENT ON COLUMN dec2010_pl94.geoheader.CONCITSC IS 'Consolidated City Size Code';
COMMENT ON COLUMN dec2010_pl94.geoheader.AIANHH IS 'American Indian Area/Alaska Native Area/ Hawaiian Home Land (Census)';
COMMENT ON COLUMN dec2010_pl94.geoheader.AIANHHFP IS 'American Indian Area/Alaska Native Area/ Hawaiian Home Land (FIPS)';
COMMENT ON COLUMN dec2010_pl94.geoheader.AIANHHCC IS 'FIPS American Indian Area/Alaska Native Area/Hawaiian Home Land Class Code';
COMMENT ON COLUMN dec2010_pl94.geoheader.AIHHTLI IS 'American Indian Trust Land/Hawaiian Home Land Indicator';
COMMENT ON COLUMN dec2010_pl94.geoheader.AITSCE IS 'American Indian Tribal Subdivision (Census)';
COMMENT ON COLUMN dec2010_pl94.geoheader.AITS IS 'American Indian Tribal Subdivision (FIPS)';
COMMENT ON COLUMN dec2010_pl94.geoheader.AITSCC IS 'FIPS American Indian Tribal Subdivision Class Code';
COMMENT ON COLUMN dec2010_pl94.geoheader.TTRACT IS 'Tribal Census Tract';
COMMENT ON COLUMN dec2010_pl94.geoheader.TBLKGRP IS 'Tribal Block Group';
COMMENT ON COLUMN dec2010_pl94.geoheader.ANRC IS 'Alaska Native Regional Corporation (FIPS)';
COMMENT ON COLUMN dec2010_pl94.geoheader.ANRCCC IS 'FIPS Alaska Native Regional Corporation Class Code';
COMMENT ON COLUMN dec2010_pl94.geoheader.CBSA IS 'Metropolitan Statistical Area/Micropolitan Statistical Area';
COMMENT ON COLUMN dec2010_pl94.geoheader.CBSASC IS 'Metropolitan Statistical Area/Micropolitan Statistical Area Size Code';
COMMENT ON COLUMN dec2010_pl94.geoheader.METDIV IS 'Metropolitan Division';
COMMENT ON COLUMN dec2010_pl94.geoheader.CSA IS 'Combined Statistical Area';
COMMENT ON COLUMN dec2010_pl94.geoheader.NECTA IS 'New England City and Town Area';
COMMENT ON COLUMN dec2010_pl94.geoheader.NECTASC IS 'New England City and Town Area Size Code';
COMMENT ON COLUMN dec2010_pl94.geoheader.NECTADIV IS 'New England City and Town Area Division';
COMMENT ON COLUMN dec2010_pl94.geoheader.CNECTA IS 'Combined New England City and Town Area';
COMMENT ON COLUMN dec2010_pl94.geoheader.CBSAPCI IS 'Metropolitan Statistical Area/Micropolitan Statistical Area Principal City Indicator';
COMMENT ON COLUMN dec2010_pl94.geoheader.NECTAPCI IS 'New England City and Town Area Principal City Indicator';
COMMENT ON COLUMN dec2010_pl94.geoheader.UA IS 'Urban Area';
COMMENT ON COLUMN dec2010_pl94.geoheader.UASC IS 'Urban Area Size Code';
COMMENT ON COLUMN dec2010_pl94.geoheader.UATYPE IS 'Urban Area Type';
COMMENT ON COLUMN dec2010_pl94.geoheader.UR IS 'Urban/Rural';
COMMENT ON COLUMN dec2010_pl94.geoheader.CD IS 'Congressional District (111th)';
COMMENT ON COLUMN dec2010_pl94.geoheader.SLDU IS 'State Legislative District (Upper Chamber) (Year 1)';
COMMENT ON COLUMN dec2010_pl94.geoheader.SLDL IS 'State Legislative District (Lower Chamber) (Year 1)';
COMMENT ON COLUMN dec2010_pl94.geoheader.VTD IS 'Voting District';
COMMENT ON COLUMN dec2010_pl94.geoheader.VTDI IS 'Voting District Indicator';
COMMENT ON COLUMN dec2010_pl94.geoheader.RESERVE2 IS 'Reserved';
COMMENT ON COLUMN dec2010_pl94.geoheader.ZCTA5 IS 'ZIP Code Tabulation Area (5-Digit)';
COMMENT ON COLUMN dec2010_pl94.geoheader.SUBMCD IS 'Subminor Civil Division (FIPS)';
COMMENT ON COLUMN dec2010_pl94.geoheader.SUBMCDCC IS 'FIPS Subminor Civil Division Class Code';
COMMENT ON COLUMN dec2010_pl94.geoheader.SDELM IS 'School District (Elementary)';
COMMENT ON COLUMN dec2010_pl94.geoheader.SDSEC IS 'School District (Secondary)';
COMMENT ON COLUMN dec2010_pl94.geoheader.SDUNI IS 'School District (Unified)';
COMMENT ON COLUMN dec2010_pl94.geoheader.AREALAND IS 'Area (Land)';
COMMENT ON COLUMN dec2010_pl94.geoheader.AREAWATR IS 'Area (Water)';
COMMENT ON COLUMN dec2010_pl94.geoheader.NAME IS 'Area Name-Legal/Statistical Area Description (LSAD) Term-Part Indicator';
COMMENT ON COLUMN dec2010_pl94.geoheader.FUNCSTAT IS 'Functional Status Code';
COMMENT ON COLUMN dec2010_pl94.geoheader.GCUNI IS 'Geographic Change User Note Indicator';
COMMENT ON COLUMN dec2010_pl94.geoheader.POP100 IS 'Population Count (100%)';
COMMENT ON COLUMN dec2010_pl94.geoheader.HU100 IS 'Housing Unit Count (100%)';
COMMENT ON COLUMN dec2010_pl94.geoheader.INTPTLAT IS 'Internal Point (Latitude)';
COMMENT ON COLUMN dec2010_pl94.geoheader.INTPTLON IS 'Internal Point (Longitude)';
COMMENT ON COLUMN dec2010_pl94.geoheader.LSADC IS 'Legal/Statistical Area Description Code';
COMMENT ON COLUMN dec2010_pl94.geoheader.PARTFLAG IS 'Part Flag';
COMMENT ON COLUMN dec2010_pl94.geoheader.RESERVE3 IS 'Reserved';
COMMENT ON COLUMN dec2010_pl94.geoheader.UGA IS 'Urban Growth Area';
COMMENT ON COLUMN dec2010_pl94.geoheader.STATENS IS 'State (ANSI)';
COMMENT ON COLUMN dec2010_pl94.geoheader.COUNTYNS IS 'County (ANSI)';
COMMENT ON COLUMN dec2010_pl94.geoheader.COUSUBNS IS 'County Subdivision (ANSI)';
COMMENT ON COLUMN dec2010_pl94.geoheader.PLACENS IS 'Place (ANSI)';
COMMENT ON COLUMN dec2010_pl94.geoheader.CONCITNS IS 'Consolidated City (ANSI)';
COMMENT ON COLUMN dec2010_pl94.geoheader.AIANHHNS IS 'American Indian Area/Alaska Native Area/ Hawaiian Home Land (ANSI)';
COMMENT ON COLUMN dec2010_pl94.geoheader.AITSNS IS 'American Indian Tribal Subdivision (ANSI)';
COMMENT ON COLUMN dec2010_pl94.geoheader.ANRCNS IS 'Alaska Native Regional Corporation (ANSI)';
COMMENT ON COLUMN dec2010_pl94.geoheader.SUBMCDNS IS 'Subminor Civil Division (ANSI)';
COMMENT ON COLUMN dec2010_pl94.geoheader.CD113 IS 'Congressional District (113th)';
COMMENT ON COLUMN dec2010_pl94.geoheader.CD114 IS 'Congressional District (114th)';
COMMENT ON COLUMN dec2010_pl94.geoheader.CD115 IS 'Congressional District (115th)';
COMMENT ON COLUMN dec2010_pl94.geoheader.SLDU2 IS 'State Legislative District (Upper Chamber) (Year 2)';
COMMENT ON COLUMN dec2010_pl94.geoheader.SLDU3 IS 'State Legislative District (Upper Chamber) (Year 3)';
COMMENT ON COLUMN dec2010_pl94.geoheader.SLDU4 IS 'State Legislative District (Upper Chamber) (Year 4)';
COMMENT ON COLUMN dec2010_pl94.geoheader.SLDL2 IS 'State Legislative District (Lower Chamber) (Year 2)';
COMMENT ON COLUMN dec2010_pl94.geoheader.SLDL3 IS 'State Legislative District (Lower Chamber) (Year 3)';
COMMENT ON COLUMN dec2010_pl94.geoheader.SLDL4 IS 'State Legislative District (Lower Chamber) (Year 4)';
COMMENT ON COLUMN dec2010_pl94.geoheader.AIANHHSC IS 'American Indian Area/Alaska Native Area/ Hawaiian Home Land Size Code';
COMMENT ON COLUMN dec2010_pl94.geoheader.CSASC IS 'Combined Statistical Area Size Code';
COMMENT ON COLUMN dec2010_pl94.geoheader.CNECTASC IS 'Combined NECTA Size Code';
COMMENT ON COLUMN dec2010_pl94.geoheader.MEMI IS 'Metropolitan/Micropolitan Indicator';
COMMENT ON COLUMN dec2010_pl94.geoheader.NMEMI IS 'NECTA Metropolitan/Micropolitan Indicator';
COMMENT ON COLUMN dec2010_pl94.geoheader.PUMA IS 'Public Use Microdata Area';
COMMENT ON COLUMN dec2010_pl94.geoheader.RESERVED IS 'Reserved';
